// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from "prisma/config";

import dotenv from "dotenv";
dotenv.config({ quiet: true });

if (!process.env["DATABASE_URL"]) {
  throw new Error("DATABASE_URL is not configured");
}
else console.log("DATABASE_URL is configured", process.env["DATABASE_URL"]);

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
